apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-servicemonitor
  namespace: monitoring          # the namespace where kube-prometheus-stack is installed
  labels:
    release: kube-prometheus    # adapt to your release name if needed
spec:
  selector:
    matchLabels:
      app: springboot
  namespaceSelector:
    matchNames:
      - springboot
  endpoints:
  - port: metrics
    path: /actuator/prometheus
    interval: 15s
