apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: springboot
  labels:
    app: springboot
spec:
  selector:
    app: bookshop
  ports:
  - name: metrics
    port: 80
    targetPort: 8081  
  type: ClusterIP